version: '3'
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:17.3.3
    container_name: teleport
    restart: always
    volumes:
      - config:/etc/teleport
      - data:/var/lib/teleport
    ports:
      - "3025:3025"
      - "3080:3080"
    command: teleport start --roles=auth,proxy --debug

volumes:
  config:
  data:
