version: v3
teleport:
  nodename: hollant
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
  proxy_server: teleport.dashlab.in:443
  auth_token: REPLACE_WITH_TOKEN
ssh_service:
  enabled: "yes"
auth_service:
  enabled: "no"
proxy_service:
  enabled: "no"
