services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:17.3.3
    container_name: teleport
    restart: always
    network_mode: "host"
    volumes:
      - ./config:/etc/teleport
      - data:/var/lib/teleport

volumes:
  data:
